- name: Install and run Nginx
  hosts: node
  tasks:
  - name: Nginx install
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Run nginx
    ansible.builtin.service:
      name: nginx
      state: started