# Variables taking from file
- name: variables from file
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"